### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by bjbjshao** [panghaibin/cx_health_sign#10]
作者你好,请问这是什么原因?在GitHub上运行.
![image](https://user-images.githubusercontent.com/105142576/175241041-92205177-c1df-4794-b996-402f45e63972.png)

**Comment by panghaibin** [comment]
看起来是调用Server酱的接口后出了问题，我这边没能复现，请确认`SendKey`是否填写正确

**Comment by bjbjshao** [comment]
好的,感谢作者,不用消息通知就不报错了.

**Comment by bjbjshao** [comment]
作者你好，我有一个账号可以成功，另一个账号同样设置却无法成功，不知道是什么原因。可以提供账号密码。

**Comment by bjbjshao** [comment]
作者你好,还有一个问题就是:我有两个账户,一样的配置,程序可以运行成功,但一个可以填写成功,另一个则不行,作者可以帮忙看看什么原因吗?
