### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by NazureWi** [panghaibin/cx_health_sign#12]
执行compare.py后程序报错
![GC5~P%%(II%5~{OKP{7844P](https://user-images.githubusercontent.com/110085699/181177086-0d181df6-99df-4694-84cd-71d32f14f27d.png)

**Comment by panghaibin** [comment]
json 文件的来源如果是通过F12-本地存储得来的，目前该方法可能已失效，参见 https://github.com/panghaibin/cx_health_sign/issues/6#issuecomment-1138122933 

现在通过模拟提交一次的方法获取json内容应该还是可行的

**Comment by NazureWi** [comment]
大佬您好，我按照您所提供的方法执行了一遍，鄙人不才，提交表单时因为无法定位而无法提交
所以能请您帮忙适配下武昌理工学院的表单嘛
账密和联系方式已经发送到您的邮箱了
不胜感激！

**Comment by NazureWi** [comment]
大佬您好，您的健康打卡程序有个bug，添加特定用户后程序会报错，打卡类型是wut，麻烦您查看一下，不胜感激！
![IMG_20220817_002550](https://user-images.githubusercontent.com/110085699/185029024-7083e958-8c49-4a74-b402-688959ad947f.jpg)
