### ISSUE TITLE
登录学习通的接口

### ISSUE THREAD

**Issue by Xiaoxusheng** [panghaibin/cx_health_sign#14]
就是登陆进去 获取token，然后进行下一步操作，我准备用其它语言写

**Comment by panghaibin** [comment]
https://github.com/panghaibin/cx_health_sign/blob/ed9007a3f2cba6e17fc5e5d75feb3fd36ac3eeb9/config/__init__.py#L54-L80

你看看你要的是这个吗

**Comment by Xiaoxusheng** [comment]
是这个
data: { result: false, opacPwd: false, errorMsg: '密码不能为空', status: '1' }
这是啥情况

**Comment by Xiaoxusheng** [comment]
我请求带密码了

**Comment by panghaibin** [comment]
贴你写的代码看看

**Comment by Xiaoxusheng** [comment]
const axios = require("axios");

//登陆学习通获取token

async function StyleSheet() {
  const res = await axios({
    method: "get",
    url: "https://passport2.chaoxing.com/api/login",
    params: {
      username: "手机号",
      password: "密码",

      verify: "0",
    },
    headers: {
      "User-Agent":
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36",
      "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
      "X-Requested-With": "XMLHttpRequest",
    },
  });

  console.log(res);
}

**Comment by panghaibin** [comment]
参数的password改成pwd

**Comment by panghaibin** [comment]
https://github.com/panghaibin/cx_health_sign/blob/ed9007a3f2cba6e17fc5e5d75feb3fd36ac3eeb9/config/__init__.py#L64

**Comment by Xiaoxusheng** [comment]
ok了参数正确谢谢博主
