### ISSUE TITLE
tust

### ISSUE THREAD

**Issue by bjbjshao** [panghaibin/cx_health_sign#17]
作者大大,tust貌似出问题了,获取上次填报数据为空.

**Comment by panghaibin** [comment]
![image](https://user-images.githubusercontent.com/63835145/187471372-e8738aae-5bd8-4c24-92ba-44347921d27b.png)

本地运行可以获取并填报。

如果你用的是GitHub Actions，有可能是GitHub的IP段被学习通屏蔽，先尝试下载到本地运行或者在服务器上运行看看

**Comment by LINK-URIBOH** [comment]
> ![图片](https://user-images.githubusercontent.com/63835145/187471372-e8738aae-5bd8-4c24-92ba-44347921d27b.png)
> 
> 本地运行可以获取并填报。
> 
> 如果你用的是 GitHub Actions，有可能是 GitHub 的 IP 段被学习通屏蔽，先尝试下载到本地运行或者在服务器上运行查看

在校的话表单需要填校内。这样的话，少了许多选项但是多了个校区的选项，还用原来的会报错。但是我不知道怎么改可以让他填校区。
这是表单数据里面关于选择校区的部分：
"fields":[{"hasDefaultValue":false,"visible":true,"editable":true,"values":[{"val":"滨海","isOther":false}],"options":[{"idArr":[],"score":0,"checked":false,"title":"河西"},{"idArr":[],"score":0,"checked":true,"title":"滨海"}],"verify":{"required":{}},"tip":{"imgs":[],"text":""},"defaultValueStr":"[]","label":"校区","fieldType":{"type":"string"}}]

**Comment by bjbjshao** [comment]
ok

**Comment by panghaibin** [comment]
@LINK-URIBOH 你可以先试试把代码下载到本地，在

https://github.com/panghaibin/cx_health_sign/blob/7d31e85897a3dd45cca45da9eadeaf06bb43ef88/config/tust.py#L49-L51

之间加一行 `print(f['id'])` ，变成

```python
 elif f['id'] in self._options_ids: 
    print(f['id'])
     # 下拉项选择改写为 true 
     for option in f['fields'][0]['options']: 
```

然后运行程序，看看是哪个 id 会让程序出错，从

https://github.com/panghaibin/cx_health_sign/blob/7d31e85897a3dd45cca45da9eadeaf06bb43ef88/config/tust.py#L19

中删除该 id

如果出现“xxx不能为空”之类的报错，找到该选项对于的id，加到 `self._options_ids` 中

**Comment by LINK-URIBOH** [comment]
> @LINK-URIBOH你可以先试试把代码下载到本地，在
> 
> https://github.com/panghaibin/cx_health_sign/blob/7d31e85897a3dd45cca45da9eadeaf06bb43ef88/config/tust.py#L49-L51
> 
> 中间加一行`print(f['id'])`，变成
> 
> ```python
>  elif f['id'] in self._options_ids: 
>     print(f['id'])
>      # 下拉项选择改写为 true 
>      for option in f['fields'][0]['options']: 
> ```
> 
> 然后程序，查看是哪个 id 运行程序出错，从
> 
> https://github.com/panghaibin/cx_health_sign/blob/7d31e85897a3dd45cca45da9eadeaf06bb43ef88/config/tust.py#L19
> 
> 中删除该id
> 
> 如果出现“xxx不能为空”之类的报错，该选项适合的id，加到`self._options_ids`中

多谢大佬，删除self._options_ids中的58就可以了。
