### ISSUE TITLE
希望大佬能适配一下河北艺术职业学院的表单

### ISSUE THREAD

**Issue by SunYaQinQwQ** [panghaibin/cx_health_sign#5]
鄙人不才，研究了很久也没法让自己适配的表单通过测试，还望大佬能百忙中抽空帮忙做一下，万分感激🙏
id=886
enc=c8f7d4f5599544933f7c222b6b44e5c4
注：每日需要两次打卡

**Comment by panghaibin** [comment]
![image](https://user-images.githubusercontent.com/63835145/162602509-651df5ab-6c78-409a-b412-0ac7a1028a4d.png)

这边适配好了，你下载试试看。至于一天打卡两次的需求，你可以设置程序一天运行两次即可

另外可以问问你是怎么适配的吗，是出现了什么报错信息？我适配的时候也没有特别修改别的地方，照理说按照我那个适配方法是可以适配成功的

**Comment by SunYaQinQwQ** [comment]
首先再次感谢大佬，问题是出在了最后一步运行控制台测试的时候，会返回如下信息
PS C:\Users\****\Desktop\cx_health_sign-master> python main.py
Traceback (most recent call last):
  File "C:\Users\****\Desktop\cx_health_sign-master\main.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by panghaibin** [comment]
这是因为依赖没有安装，执行
```
pip install -r requirements.txt
```
安装一下依赖
