### ISSUE TITLE
现在已经不行了吗，F12本地存储里找不到表单数据了[受虐滑稽]

### ISSUE THREAD

**Issue by Akunxin** [panghaibin/cx_health_sign#6]
现在已经不行了吗，F12本地存储里找不到表单数据了[受虐滑稽]

**Comment by panghaibin** [comment]
表单链接发一下？我刚刚看还是能找到的

**Comment by Akunxin** [comment]
https://office.chaoxing.com/front/apps/forms/fore/apply?id=200487&amp;formAppId=&amp;enc=b69dd988598ff61b4366fdb1f1962114&amp;appId=49161578a9704d7ca4b837e0ecd00c7e&amp;appKey=5y7hWB737k10dk20&amp;fidEnc=b807e0d034749a56&amp;uid=157067734&amp;mappId=6634500&amp;code=1aSxwHr2&amp;state=170642



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月26日(周四) 上午9:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [panghaibin/cx_health_sign] 现在已经不行了吗，F12本地存储里找不到表单数据了[受虐滑稽] (Issue #6)




 
表单链接发一下？我刚刚看还是能找到的

**Comment by Akunxin** [comment]
https://office.chaoxing.com/front/apps/forms/fore/apply?id=200487&formAppId=&enc=b69dd988598ff61b4366fdb1f1962114&appId=49161578a9704d7ca4b837e0ecd00c7e&appKey=5y7hWB737k10dk20&fidEnc=b807e0d034749a56&uid=157067734&mappId=6634500&code=1aSxwHr2&state=170642

**Comment by Akunxin** [comment]
![image](https://user-images.githubusercontent.com/30563616/170406590-a4df3bce-08c1-45da-b765-7f0ea8d5f571.png)
这边没有看到本地存储的表单数据

**Comment by Akunxin** [comment]
![image](https://user-images.githubusercontent.com/30563616/170406820-00513153-2b90-4197-8071-a048b27fdaef.png)
别的学校表单页能看到这条,我的不行诶

**Comment by panghaibin** [comment]
@Akunxin  看到了，确实是这样

不知道你在浏览器上是否能正常提交，如果可以的话，模拟一次提交后，找到 `save` 开头的请求，将 `formData` 的内容作为 json 文件的内容保存下来，再运行试试看

![image](https://user-images.githubusercontent.com/63835145/170412107-d902b48f-f048-4755-8bb6-f95e43d8415c.png)

**Comment by Akunxin** [comment]
好的，浏览器可以正常提交，0点我再抓看看，谢谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月26日(周四) 中午11:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [panghaibin/cx_health_sign] 现在已经不行了吗，F12本地存储里找不到表单数据了[受虐滑稽] (Issue #6)




 
@Akunxin  看到了，确实是这样
 
不知道你在浏览器上是否能正常提交，如果可以的话，模拟一次提交后，找到 save 开头的请求，将 formData 的内容作为 json 文件的内容保存下来，再运行试试看

**Comment by Akunxin** [comment]
方法确实有效,成功了,有个问题就是这个时间是自动获取的,用脚本提交不是自动获取的,会是和前一天的表单相同,就像位置信息一样
![11B4F72DDA0C0A500D1601072741601A](https://user-images.githubusercontent.com/30563616/170543733-1f5f9875-1343-4675-ad35-f28543b49127.jpg)

**Comment by Akunxin** [comment]
这个时间不是selfdayid,改-1无效~不过问题不大

**Comment by panghaibin** [comment]
程序是通过匹配表单字段的格式是否为`yyyy-MM-dd`，来判断该字段是否是打卡时间。这个表单除了打卡时间用了这个格式，还有一个“昨日日期”也是这个格式，所以会造成程序自动匹配出错。

![image](https://user-images.githubusercontent.com/63835145/170549518-9cbb2626-09fc-4dcd-bde7-53819d0d1cee.png)

![image](https://user-images.githubusercontent.com/63835145/170549484-84f5b9b9-8ef7-458f-9961-60d8df99aa16.png)

所以试试改成

```python
self._day_id = 73
```

看看

**Comment by Xiaoxusheng** [comment]
大佬学习通登录接口发一下我怎么登不上去了

**Comment by panghaibin** [comment]
@ehbcifnfn 
> 大佬学习通登录接口发一下我怎么登不上去了

首先，如果遇到新的问题，可以新开一个 issue
其次，登录接口指的是？你可以直接看一下源码，有相关的登录操作

**Comment by Auroru1004** [comment]
大佬为什么我用github action显示list index out of range

**Comment by panghaibin** [comment]
@Auroru1004 

> 大佬为什么我用github action显示list index out of range

你所用的表单（学校）是？
是第一次使用就不行，还是正常使用一段时间后出现错误？
表单内容是否有过更改？如果是，更改后需要手动打卡一次，程序才能获取正确的信息；如果手动打卡后再次尝试依然不行，则可能需要重新适配。

**Comment by Auroru1004** [comment]
正常使用一段时间后出现错误，我所使用的学校表单是tust

**Comment by Auroru1004** [comment]
获取上次tust早检表单提交数据为空,但是提前我手动打卡了的

**Comment by Auroru1004** [comment]
![screenshot-office chaoxing com-2022 08 30-17_06_54](https://user-images.githubusercontent.com/104885451/187397619-b8333817-94ed-42f4-97d0-36dcd16fd84d.png)

**Comment by panghaibin** [comment]
@Auroru1004 可能需要一个测试账号才能排查，如果可以请将账密发到我邮箱 i@hbte.ch 。可以附上联系方式如QQ等。

**Comment by Auroru1004** [comment]
好的

**Comment by Akunxin** [comment]
我这边也是表单更新了,添加了新的内容,出现了IndexError: list index out of range\n']

**Comment by Akunxin** [comment]
我这边也是表单更新了,添加了新的内容,出现了IndexError: list index out of range\n'],我排查了一下新加入的选项,有一些解析出来的是选择特定选项后才会多出来的选项,但是也被解析出来了,我把它们删掉就好了
![原因](https://user-images.githubusercontent.com/30563616/187847595-71daef4f-bae0-4ecb-850d-7b63a3da2994.png)
