### ISSUE TITLE
希望大佬可以适配一下河北农业大学

### ISSUE THREAD

**Issue by h88782481** [panghaibin/cx_health_sign#8]
id=204160
enc=a9b79f8b76307cd50a458b843d219ff2
自己弄了半天也没有找到表单数据

**Comment by panghaibin** [comment]
看了一下，可能是新的表单不存储数据在本地了。这需要手动在浏览器提交一次，找到 `save` 开头的请求，将 `formData` 的内容作为 json 文件的内容保存下来，再运行试试看

详见之前的一个 issue: https://github.com/panghaibin/cx_health_sign/issues/6#issuecomment-1138122933

**Comment by h88782481** [comment]
不行，根据抓包之后的结果在适配了以后显示填报日期值不能为空

**Comment by panghaibin** [comment]
> 不行，根据抓包之后的结果在适配了以后显示填报日期值不能为空

@h88782481 可以把抓包的 `formData` 内容作为附件发到我邮箱吗？ i@hbte.ch

**Comment by h88782481** [comment]
> > 不行，根据抓包之后的结果在适配了以后显示填报日期值不能为空
> 
> @h88782481 可以把抓包的 `formData` 内容作为附件发到我邮箱吗？ [i@hbte.ch](mailto:i@hbte.ch)

已经发送到你的邮箱了，并附上了我的联系qq，如果可以的话希望能加上qq

**Comment by panghaibin** [comment]
@h88782481 收到邮件了，尝试适配了一下，但是没有账号无法测试。QQ已申请添加了，还未通过验证。

**Comment by h88782481** [comment]
> @h88782481 收到邮件了，尝试适配了一下，但是没有账号无法测试。QQ已申请添加了，还未通过验证。

不好意思，我这里并未收到添加好友的申请，如果可以的话请往2854925836@qq.com发送联系方式
