### ISSUE TITLE
能否适配天津科技大学的表单

### ISSUE THREAD

**Issue by ayahana** [panghaibin/cx_health_sign#9]
大佬，能适配一下天津科技大学的表单吗，想在服务器上运行，然后手机抓包抓不下来，搞了两天，奔溃了

**Comment by panghaibin** [comment]
id 和 enc 抓到了吗？没有的话请把测试账号和密码发我邮箱 [i@hbte.ch](mailto:i@hbte.ch)

**Comment by bjbjshao** [comment]
好校友怎么样了,适配了吗.

**Comment by ayahana** [comment]
> 好校友怎么样了,适配了吗.

正在尝试中

**Comment by bjbjshao** [comment]
好的加油祝你成功

**Comment by panghaibin** [comment]
@ayahana  @bjbjshao  适配好了，可以试试

**Comment by bjbjshao** [comment]
请问代码是?没找到....

**Comment by bjbjshao** [comment]
看见了,谢谢谢谢
